### ISSUE TITLE
num_partitions is not being passed to GSPMD Pipeline for pjit.

### ISSUE THREAD

**Issue by trevor-m** [openxla/openxla-pjrt-plugin#150]
We will need to pass `num_partitions` from jax to the GSPMD partitioner when using pjit.

## Expected Behavior

Program output should be 4 when running with 4 devices.
```
$ JAX_PLATFORMS=iree_cuda mpirun -np 4 -quiet python test_pjit_mpi.py
4.0
```

## Actual Behavior

Progress crashes with input shape mismatch since program is not partitioned.

```
Traceback (most recent call last):
  File "/workspace/openxla-pjrt-plugin/test/test_pjit_mpi.py", line 23, in <module>
    test_pjit_mpi()
  File "/workspace/openxla-pjrt-plugin/test/test_pjit_mpi.py", line 19, in test_pjit_mpi
    y = jax.jit(_psum, out_shardings=jax.sharding.NamedSharding(global_mesh, P()))(x)
  File "/workspace/jax/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/workspace/jax/jax/_src/pjit.py", line 212, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/workspace/jax/jax/_src/pjit.py", line 159, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/workspace/jax/jax/_src/core.py", line 2647, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/workspace/jax/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/workspace/jax/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/workspace/jax/jax/_src/pjit.py", line 1123, in _pjit_call_impl
    return compiled.unsafe_call(*args)
  File "/workspace/jax/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/workspace/jax/jax/_src/interpreters/pxla.py", line 1349, in __call__
    results = self.xla_executable.execute_sharded(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: external/iree_core/runtime/src/iree/modules/hal/utils/buffer_diagnostics.c:225: INVALID_ARGUMENT; input 0 shape dimension 0 mismatch; expected 4 but have 1; expected shape `4`, actual shape `1`; while invoking native function hal.buffer_view.assert; while calling import;
[ 1]   native hal.buffer_view.assert:0 -
[ 0] bytecode jit__psum.main:194 <jit>:2:3
```

## Steps to Reproduce the Problem

1. Checkout [Use OpenMPI to run multiple clients #116](https://github.com/openxla/openxla-pjrt-plugin/pull/116)
2. Make sure the partitioner is enabled: `export IREE_PJRT_PARTITIONER_LIB_PATH=/workspace/openxla/openxla-pjrt-plugin/bazel-bin/partitioner/libOpenXLAPartitioner.so`.
3. Run the following using `JAX_PLATFORMS=iree_cuda mpirun -np 4 -quiet python3 test_pjit_mpi.py`. You can also do 2 devices instead using `-np 2`.
```
#test_pjit_mpi.py
import jax
import jax.numpy as jnp
import numpy as np
from jax.sharding import PartitionSpec as P
from functools import partial

def _psum(x):
  return jnp.sum(x, axis=0)

def test_pjit_mpi():
    jax.distributed.initialize()
    devices = np.array(jax.devices()).reshape(jax.process_count(), jax.local_device_count())
    global_mesh = jax.sharding.Mesh(devices, ('processes', 'local_devices'))
    pspec = P('processes')

    x = jax.numpy.ones([jax.local_device_count()])
    x = jax.experimental.multihost_utils.host_local_array_to_global_array(x, global_mesh, pspec)
    y = jax.jit(_psum, out_shardings=jax.sharding.NamedSharding(global_mesh, P()))(x)
    if jax.process_index() == 0:
        print(y)

test_pjit_mpi()
```
4. The program will crash with the above error. If you hardcode [num_partitions=4 here or however many devices you are using](https://github.com/openxla/openxla-pjrt-plugin/blob/main/partitioner/src/openxla/partitioner/GSPMDPipeline.cpp#L191), then the program will run successfully and give the correct output.

**Comment by trevor-m** [comment]
cc @okkwon

**Comment by stellaraccident** [comment]
Do we have documented how to run distributed like this?

FTR: https://github.com/openxla/openxla-pjrt-plugin/blob/main/iree/integrations/pjrt/common/api_impl.cc#L1109

(needs to set the flag https://github.com/openxla/openxla-pjrt-plugin/blob/main/partitioner/src/openxla/partitioner/GSPMDPipeline.cpp#L134)

**Comment by trevor-m** [comment]
Nice, thanks for the pointers. Will give it a try tomorrow

**Comment by okkwon** [comment]
Yep. This issue is to make the plumbing right. Thanks @trevor-m for taking a stab at it.

Just FYI, other missing parts are `PJRT_Executable_NumReplicas and PJRT_Executable_NumPartitions. They are hard-coded to return 1. However, they are not called in the model run, so they don't affect the codegen at the moment.

**Comment by stellaraccident** [comment]
@okkwon Part of the reason I left a TODO was that I didn't know which wires were actually connected at the PJRT level, and asking was beyond my capabilities when I wrote this.

There is also a serialized CompilationOptions proto which alleges to carry this information. But I don't trust that any of it is plumbed properly... Would be good to have a solid answer on that.

**Comment by okkwon** [comment]
Right. Many things are unknown at the dev time, since the API calling sequence was unknown. We keep discovering things here and there. I am closely working with Trevor. We will figure out.

**Comment by stellaraccident** [comment]
Ok, let me know if I can help, and/or call in the PJRT folks.

**Comment by trevor-m** [comment]
Looks like the CompilationOptions proto has the correct num partitions, so I was able to read that and pass it to the partitioner:
https://github.com/trevor-m/openxla-pjrt-plugin/commit/7857475950d4a25cee7616489bac052a2cbb3c68

@stellaraccident @okkwon

**Comment by stellaraccident** [comment]
Nice! Put that in a PR and we can merge it!
