### ISSUE TITLE
chlo.erf_inv unsupported by partitioner 

### ISSUE THREAD

**Issue by trevor-m** [openxla/openxla-pjrt-plugin#159]
Jax uses [`erf_inv` during `jax.random.normal()`](https://github.com/google/jax/blob/525ba49ba73eade3e0dce285f4f4681d9dd8e5d5/jax/_src/random.py#L648). The partitioner gives an error when it encounters `chlo.erf_inv`.

## Expected Behavior

Partitioning should succeed.

## Actual Behavior

```
<unknown>:0: error: failed to convert mhlo to hlo: UNKNOWN: /opt/praxis/praxis/base_layer.py:691:0: error: 'chlo.erf_inv' op unsupported op for export to XLA
/opt/praxis/praxis/base_layer.py:691:0: note: see current operation: %3 = "chlo.erf_inv"(%2) : (tensor<2048x51200xf32>) -> tensor<2048x51200xf32>
```

## Steps to Reproduce the Problem

Run the partitioner on the following MLIR program using `openxla-partitioner repro.mlir`

```
module @jit_init_fn attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2048x51200xf32> loc(unknown)) -> tensor<2048x51200xf32> {
    %0 = chlo.erf_inv %arg0 : tensor<2048x51200xf32> -> tensor<2048x51200xf32> loc(unknown)
    return %0 : tensor<2048x51200xf32> loc(unknown)
  }
}
```

**Comment by stellaraccident** [comment]
This is why gspmd and the old HLO passes are going to be problematic in the long run.

We have two options for such things:
* We transcribe such non standard ops as a form of custom_call in a way that gspmd can handle them.
* We run the passes to expand CHLO to stablehlo.
