### ISSUE TITLE
Setup JAX/PJRT Regression workflow in OpenXLA PJRT Plugin

### ISSUE THREAD

**Issue by rsuderman** [openxla/openxla-pjrt-plugin#49]
We should have some basic regression testing in the OpenXLA PJRT plugin repo. Pick a couple of files and run tests, then filter down to the passing tests to watch for regressions. This should be running as a github action nightly with the iree nightly build.

**Comment by allieculp** [comment]
@rsuderman Any update here? Still relevant as written?

**Comment by jpienaar** [comment]
I think this works well enough at the moment. At least for basic as phrased here.
