### ISSUE TITLE
Known test in lax_numpy_test.py thread locks

### ISSUE THREAD

**Issue by rsuderman** [openxla/openxla-pjrt-plugin#59]
Some tests have been known to stall out the pjrt plugin, we have not triaged why this occurs. Below is an isolated test that is known to threadlock for unknown reasons.

```
JAX_PLATFORMS=iree_cpu pytest --max-worker-restart=9999   -p openxla_pjrt_artifacts --openxla-pjrt-artifact-dir=/tmp/jaxtest external/jax/tests/lax_numpy_test.py::LaxBackedNumpyTests::testArgMinMaxEmpty0
```

**Comment by allieculp** [comment]
@aaron-schneider @rsuderman Do we have an owner for this P1?

**Comment by ramiro050** [comment]
@rsuderman, unable to recreate. Test passes locally. Is this something you're seeing on CI?

**Comment by jpienaar** [comment]
This is rather old at this point, I propose we close unless we can see locally.
